// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDF4NMl-LOjsNC-vamsAEiZ4202ts--bXg',
    appId: '1:260713749976:web:fad8358868c166e67e66ad',
    messagingSenderId: '260713749976',
    projectId: 'phoneath-db7d4',
    authDomain: 'phoneath-db7d4.firebaseapp.com',
    databaseURL: 'https://phoneath-db7d4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'phoneath-db7d4.appspot.com',
    measurementId: 'G-RBMNWT1S3L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_FMDFSx-oEls9JpF4-6aWJwOihkAKXh8',
    appId: '1:260713749976:android:246c1656982ecced7e66ad',
    messagingSenderId: '260713749976',
    projectId: 'phoneath-db7d4',
    databaseURL: 'https://phoneath-db7d4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'phoneath-db7d4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDsKXGnZOwB9U8RiVdlAVEvkrLcTih0vU',
    appId: '1:260713749976:ios:535f2540aa92d5197e66ad',
    messagingSenderId: '260713749976',
    projectId: 'phoneath-db7d4',
    databaseURL: 'https://phoneath-db7d4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'phoneath-db7d4.appspot.com',
    iosClientId: '260713749976-r6n7qqqb6bfok5dm9r47crethn6v0nco.apps.googleusercontent.com',
    iosBundleId: 'com.example.pro1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbHM7yQ6fG2BOrsCqIGf8a26M180JGNVI',
    appId: '1:260713749976:ios:1769510c4c9fa4d87e66ad',
    messagingSenderId: '260713749976',
    projectId: 'phoneath-db7d4',
    databaseURL: 'https://phoneath-db7d4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'phoneath-db7d4.appspot.com',
    iosBundleId: 'com.example.pro1.RunnerTests',
  );
}
