name: pro2
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  cloud_firestore: ^4.15.0
  country_picker: ^2.0.24
  cupertino_icons: ^1.0.6
  firebase_analytics: ^10.8.1
  firebase_auth: ^4.17.0
  firebase_core: ^2.25.0
  firebase_crashlytics: ^3.4.10
  firebase_database: ^10.4.1
  firebase_storage: ^11.6.1
  flutter:
    sdk: flutter
  intl: ^0.19.0
  pinput: ^3.0.1
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  custom_line_indicator_bottom_navbar: ^0.0.8
  icon: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
