name: pro1
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  country_picker: ^2.0.23
  firebase_core: ^2.24.2
  firebase_analytics: ^10.8.0
  firebase_crashlytics: ^3.4.9
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  firebase_storage: ^11.6.0
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  pinput: ^3.0.1
  intl: ^0.19.0
  firebase_database: ^10.4.0
  molten_navigationbar_flutter: ^1.0.1
  timer_count_down: ^2.2.2
  custom_line_indicator_bottom_navbar: ^0.0.8
  firebase_messaging: ^14.7.16
  qr_flutter: ^4.1.0
  path_provider: ^2.1.2
  image_gallery_saver: ^2.0.3
  overlay_support: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
